### ISSUE TITLE
Rough checklist for bonding curve uses cases Arc should cover

### ISSUE THREAD

**Issue by lsaether** [convergentcx/Arc#2]
Props to this checklist goes to Paul / Achill:
 - [ ] **Dilution by curve creator**: AKA the "pre-mine" or when the creator mints a certain amount of tokens for themselves at the creation of the curve so that as the market buys from the curve he/she will have their original tokens diluted.
 - [ ] **Discounting curves**: TODO: see Wilson Lau's original article for explanation of this.
 - [ ] **Staking returns from the curve**: TODO: same as above
 - [X] **Double curve**: AKA the "buy-sell-spread". (Merged in #10 )
 - [ ] **Taxation**: AKA the "rent-seeker". Charge a small premium for all operations on the curve. Liquidity will always back the curve, but the owner will make small _tax_.
 - [ ] **Sponsored Burn**. Increase the total Supply of the tokens without minting new tokens in circulation. Adds reserve asset without creating new bonded token.
- [ ] **Equilibrium Bonding** More info [here](https://blog.oceanprotocol.com/introducing-the-equilibrium-bonding-market-e7db528e0eff)

**Comment by acrdlph** [comment]
I wonder if this is already covered by the above models: https://medium.com/@avsa/sponsored-burning-for-tcr-c0ab08eef9d4

**Comment by lsaether** [comment]
@acrlph Nope I think that's another variant. Will add it to the original list.

**Comment by acrdlph** [comment]
the equilibrium bonding market probably belongs here too: basically a bonding curve that caps off at a certain point - https://blog.oceanprotocol.com/introducing-the-equilibrium-bonding-market-e7db528e0eff

**Comment by lsaether** [comment]
@acrdlph added

**Comment by lsaether** [comment]
Checked off the double curve since it was introduced in PR #10 and will make it into the next release of Arc `v0.0.4`. Next on the list if probably the premium models since this is pretty straightforward to implement.

**Comment by lsaether** [comment]
Also worth keeping track of these blog posts from Slava and Billy about the bancor formula:
https://blog.relevant.community/bonding-curves-in-depth-intuition-parametrization-d3905a681e0a
https://medium.com/@billyrennekamp/converting-between-bancor-and-bonding-curve-price-formulas-9c11309062f5

Since we currently use the simpler model of y = m * x^n, the first link especially mentions the constraint of this in Solidity being that it limits the total supply of tokens due to potential overflows. We may want to move back to using the Bancor formula contract ... probably reintroduce this at a later date and opening a new issue to keep track of it.
